name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login into Docker
      run: docker login --username "${username}" --password "${password}"
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: bash build_docker.sh "${GITHUB_REF:10}"
