name: Go
on: repository_dispatch
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: $github	
      run:   echo "$GITHUB_CONTEXT"	
      env:	
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
          ref: ${{ client_payload.ref }}
    - name: Build
      run: |
        sh  build.sh
    - name: Move artifacts
      run: |
        mkdir artifacts && mv src/cryptocli/cryptocli-*.zip artifacts
    - name: upload
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: artifacts
